name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: speechActs
          environment-file: environment.yml
          auto-activate-base: false
          python-version: 3.7

      - name: Install the library
        run: |
          conda activate speechActs
          pip install -e .

      - name: Read all notebooks
        run: |
          conda activate speechActs
          nbdev_read_nbs

      - name: Check if all notebooks are cleaned
        run: |
          conda activate speechActs
          echo "Check we are starting with clean git checkout"
          if [ -n "$(git status -uno -s)" ]; then echo "git status is not clean"; false; fi
          echo "Trying to strip out notebooks"
          nbdev_clean_nbs
          echo "Check that strip out was unnecessary"
          git status -s # display the status to see which nbs need cleaning up
          if [ -n "$(git status -uno -s)" ]; then echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_git_hooks"; false; fi

      - name: Check if there is no diff library/notebooks
        run: |
          conda activate speechActs
          if [ -n "$(nbdev_diff_nbs)" ]; then echo -e "!!! Detected difference between the notebooks and the library"; false; fi

      - name: Run tests
        run: |
          conda activate speechActs
          nbdev_test_nbs
